### ISSUE TITLE
Failed to flush outgoing items {:outgoing_count=>1, :exception=>"NoMethodError",

### ISSUE THREAD

**Issue by ecw-rmenon** [yokawasa/logstash-output-azuresearch#5]
@yokawasa 

Getting the below error while trying to run the plugin. 
Logstash version: 6.6.0
config used is the one in examples JSON_LINES
[[main]>worker0] azuresearch - Failed to flush outgoing items {:outgoing_count=>1, :exception=>"NoMethodError", :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-azuresearch-0.1.2/lib/logstash/outputs/azuresearch.rb:77:in `block in flush'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-azuresearch-0.1.2/lib/logstash/outputs/azuresearch.rb:70:in `flush'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/buffer.rb:219:in `block in buffer_flush'", "org/jruby/RubyHash.java:1343:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/buffer.rb:216:in `buffer_flush'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/buffer.rb:159:in `buffer_receive'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-azuresearch-0.1.2/lib/logstash/outputs/azuresearch.rb:62:in `receive'", "/usr/share/logstash/logstash-core/lib/logstash/outputs/base.rb:89:in `block in multi_receive'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/outputs/base.rb:89:in `multi_receive'", "org/logstash/config/ir/compiler/OutputStrategyExt.java:114:in `multi_receive'", "org/logstash/config/ir/compiler/AbstractOutputDelegatorExt.java:97:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:373:in `block in output_batch'", "org/jruby/RubyHash.java:1343:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:372:in `output_batch'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:324:in `worker_loop'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:287:in `block in start_workers'"]}

**Comment by TNAravind** [comment]
Hello @ecw-rmenon @yokawasa @denzuko 

Were you able to find any solution for the above issue. We are facing the same issue, and this is causing inconsistent data synchronization. Also, we are not able to use this plugin with the latest versions of the logstash other than logstash version 8.6.2. If you have the solution, please help.

Thank you
Aravind
